CREATE TABLE consumers
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(30)                             NOT NULL,
    lastname  VARCHAR(30),
    login     VARCHAR(10)                             NOT NULL,
    password  VARCHAR(10)                             NOT NULL,
    role      VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_consumers PRIMARY KEY (id)
);

CREATE TABLE contact
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telephone VARCHAR(11)                             NOT NULL,
    email     VARCHAR(100)                            NOT NULL,
    telegram  VARCHAR(30),
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

CREATE TABLE contact_registration
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consumer_id    BIGINT,
    contact_id     BIGINT,
    date_registred date,
    CONSTRAINT pk_contactregistration PRIMARY KEY (id)
);