CREATE TABLE candidate
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(30)                             NOT NULL,
    lastname  VARCHAR(30)                             NOT NULL,
    file_name VARCHAR(100)                            NOT NULL,
    status_id BIGINT,
    CONSTRAINT pk_candidate PRIMARY KEY (id)
);

CREATE TABLE client
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname    VARCHAR(30)                             NOT NULL,
    lastname     VARCHAR(30),
    name_company VARCHAR(100),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE consumers
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(30)                             NOT NULL,
    lastname  VARCHAR(30)                             NOT NULL,
    login     VARCHAR(10)                             NOT NULL,
    password  VARCHAR(10)                             NOT NULL,
    role      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_consumers PRIMARY KEY (id)
);

CREATE TABLE contact
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telephone VARCHAR(11)                             NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    telegram  VARCHAR(30),
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

CREATE TABLE contact_registration
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consumer_id BIGINT,
    contact_id  BIGINT,
    client_id   BIGINT,
    CONSTRAINT pk_contactregistration PRIMARY KEY (id)
);

CREATE TABLE respond
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_respond BIGINT,
    vacancy_id     BIGINT,
    CONSTRAINT pk_respond PRIMARY KEY (id)
);

CREATE TABLE status
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_begin  date,
    date_end    date,
    name_status VARCHAR(255),
    CONSTRAINT pk_status PRIMARY KEY (id)
);

CREATE TABLE vacancy
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_vacancy       VARCHAR(50)                             NOT NULL,
    number_declaration BIGINT                                  NOT NULL,
    url_sources        VARCHAR(255)                            NOT NULL,
    client_id          BIGINT,
    status_id          BIGINT,
    CONSTRAINT pk_vacancy PRIMARY KEY (id)
);

ALTER TABLE candidate
    ADD CONSTRAINT FK_CANDIDATE_ON_STATUS FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE contact_registration
    ADD CONSTRAINT FK_CONTACTREGISTRATION_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE contact_registration
    ADD CONSTRAINT FK_CONTACTREGISTRATION_ON_CONSUMER FOREIGN KEY (consumer_id) REFERENCES consumers (id);

ALTER TABLE contact_registration
    ADD CONSTRAINT FK_CONTACTREGISTRATION_ON_CONTACT FOREIGN KEY (contact_id) REFERENCES contact (id);

ALTER TABLE respond
    ADD CONSTRAINT FK_RESPOND_ON_VACANCY FOREIGN KEY (vacancy_id) REFERENCES vacancy (id);

ALTER TABLE vacancy
    ADD CONSTRAINT FK_VACANCY_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE vacancy
    ADD CONSTRAINT FK_VACANCY_ON_STATUS FOREIGN KEY (status_id) REFERENCES status (id);