CREATE TABLE contacts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telephone    VARCHAR(255)                            NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    recruiter_id BIGINT,
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);

CREATE TABLE recruiters
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    login    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_recruiters PRIMARY KEY (id)
);

ALTER TABLE contacts
    ADD CONSTRAINT FK_CONTACTS_ON_RECRUITER FOREIGN KEY (recruiter_id) REFERENCES recruiters (id);