CREATE TABLE candidate
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(30)                             NOT NULL,
    lastname  VARCHAR(30)                             NOT NULL,
    file_name VARCHAR(100)                            NOT NULL,
    status_id BIGINT,
    CONSTRAINT pk_candidate PRIMARY KEY (id)
);

CREATE TABLE client
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname    VARCHAR(30)                             NOT NULL,
    lastname     VARCHAR(30),
    name_company VARCHAR(100),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE consumers
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname VARCHAR(100)                             NOT NULL,
    lastname  VARCHAR(100)                             NOT NULL,
    login     VARCHAR(100)                             NOT NULL,
    password  VARCHAR(100)                             NOT NULL,
    role      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_consumers PRIMARY KEY (id)
);

CREATE TABLE contact
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    telephone VARCHAR(100)                             NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    telegram  VARCHAR(100),
    CONSTRAINT pk_contact PRIMARY KEY (id)
);

CREATE TABLE contact_registration
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    consumer_id BIGINT,
    contact_id  BIGINT,
    client_id   BIGINT,
    CONSTRAINT pk_contactregistration PRIMARY KEY (id)
);

CREATE TABLE respond
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_respond VARCHAR(255),
    vacancy_id     BIGINT,
    CONSTRAINT pk_respond PRIMARY KEY (id)
);

CREATE TABLE status
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_begin  date,
    date_end    date,
    name_status VARCHAR(255),
    CONSTRAINT pk_status PRIMARY KEY (id)
);

CREATE TABLE vacancy
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_vacancy       VARCHAR(255)                             NOT NULL,
    client_id          BIGINT,
    status_id          BIGINT,
    CONSTRAINT pk_vacancy PRIMARY KEY (id)
);

CREATE TABLE vacancy_candidate
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255),
    url_source VARCHAR(255),
    vacancy_id BIGINT,
    candidate_id BIGINT,
    CONSTRAINT pk_vacancycandidate PRIMARY KEY (id)
);