CREATE TABLE vacancy_candidate
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255),
    url_source VARCHAR(255),
    vacancy_id BIGINT,
    CONSTRAINT pk_vacancycandidate PRIMARY KEY (id)
);

ALTER TABLE candidate
    ADD file_name_resume VARCHAR(100);

ALTER TABLE candidate
    ALTER COLUMN file_name_resume SET NOT NULL;

ALTER TABLE vacancy_candidate
    ADD CONSTRAINT FK_VACANCYCANDIDATE_ON_VACANCY FOREIGN KEY (vacancy_id) REFERENCES vacancy (id);

ALTER TABLE vacancy_candidate
    ADD CONSTRAINT FK_VACANCYCANDIDATE_ON_VACANCYmguRaX FOREIGN KEY (vacancy_id) REFERENCES candidate (id);

ALTER TABLE candidate
DROP
COLUMN file_name;